server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: merge-events-auth-services
          uri: https://github.com/LouisGonzalez/2package
          search-paths: /microservices/config-data
  application:
    name: config-service
