server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: auth-service-prototype-luis
          uri: https://github.com/LouisGonzalez/2package
          search-paths: /microservices/config-data
  application:
    name: config-service
