server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost
  
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: test-service
          uri: lb://test-service
          predicates:
            - Path=/user/**
          filters:
            - AuthFilter



        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**            

        - id: checkpoints-service
          uri: lb://checkpoints-service
          predicates:
            - Path=/checkpoints/**

        - id: pagos-service
          uri: lb://pagos-service
          predicates:
            - Path=/pagos/**

        - id: paquetes-service
          uri: lb://paquetes-service
          predicates:
            - Path=/paquetes/**

        - id: rutas-service
          uri: lb://rutas-service
          predicates:
            - Path=/rutas/**

        - id: usuarios-service
          uri: lb://usuarios-service
          predicates:
            - Path=/usuarios/**